# Generated by Django 6.0.2 on 2026-07-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('local_church', models.CharField(max_length=150, verbose_name='Église locale')),
                ('congregation', models.CharField(max_length=150, verbose_name='Congrégation')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('quality', models.CharField(choices=[('responsable', 'Responsable'), ('pasteur', 'Pasteur'), ('etudiant_pasteur', 'Étudiant pasteur')], max_length=30, verbose_name='Qualité')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='participants/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
