# Generated by Django 6.0.2 on 2026-07-21 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='country',
            field=models.CharField(choices=[('CM', 'Cameroun'), ('CF', 'République centrafricaine'), ('TD', 'Tchad'), ('GA', 'Gabon'), ('CG', 'Congo'), ('CD', 'République démocratique du Congo'), ('CI', "Côte d'Ivoire"), ('SN', 'Sénégal'), ('BF', 'Burkina Faso'), ('ML', 'Mali'), ('NE', 'Niger'), ('GN', 'Guinée'), ('BJ', 'Bénin'), ('TG', 'Togo'), ('FR', 'France'), ('US', 'États-Unis')], max_length=2, verbose_name='Pays'),
        ),
    ]
